### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by petel** [tcarlsen/atom-htmlhint#9]
[Enter steps to reproduce below:]

1. ...not sure sorry
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [htmlhint](https://github.com/tcarlsen/atom-htmlhint) package, v1.1.3

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at module.exports (/Users/ploring/.atom/packages/htmlhint/lib/config.coffee:6:43)
    at module.exports (/Users/ploring/.atom/packages/htmlhint/lib/linter.coffee:19:37)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1035:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:557:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:530:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:513:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:631:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -6:41.3.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:57.2.0 autocomplete-plus:cancel (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:00.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:58.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:58.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:58.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:51.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:31.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:11.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:59.8.0 core:save (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
  2x -0:17.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:12.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:11.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:04.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "emmet",
      "fold-comments",
      "img-placeholder",
      "markdown-folder",
      "jshint",
      "minimap",
      "w3c-validation",
      "linter-htmlhint",
      "linter-csslint"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-wrap-in-tag, v0.4.0
auto-indent, v0.5.0
autoclose-html, v0.19.0
autocomplete-emojis, v2.2.2
browser-plus, v0.0.54
color-picker, v2.0.13
csslint, v1.1.4
htmlhint, v1.1.3
indent-guide-improved, v1.4.4
linter, v1.11.3
linter-tidy, v1.0.1
open-in-browser, v0.4.6
pigments, v0.19.1
preview-plus, v1.2.6

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
should be fixed now in 1.1.4

**Comment by basiphobe** [comment]
This is still happening for me in 1.15.0:

![image](https://cloud.githubusercontent.com/assets/1565483/24012606/f3b367fe-0a54-11e7-9290-9c18612478f1.png)

**Comment by basiphobe** [comment]
Here's the stack trace:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at module.exports (file:///C:/Users/ajsmith/.atom/packages/htmlhint/lib/config.coffee:6:43)
    at module.exports (file:///C:/Users/ajsmith/.atom/packages/htmlhint/lib/linter.coffee:19:37)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1082:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1048:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:915:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\src\pane.js:753:18)
    at Pane.saveItem (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\src\pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\src\pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\src\workspace.js:693:35)
    at atom-workspace.core:save (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\src\register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\ajsmith\AppData\Local\atom\app-1.15.0\resources\app.asar\src\window-event-handler.js:3:59)
```
